<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-Christopherlopmx/blob/main/IBM_Semana_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [ ]:
print (a[1])

1


In [ ]:
# import numpy library

import numpy as np 

In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [ ]:
type (a)

numpy.ndarray

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [ ]:
print(np.__version__)

1.21.6


In [ ]:
type (a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here


In [ ]:
type (b)

numpy.ndarray

In [ ]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [ ]:
type (c)

numpy.ndarray

In [ ]:
c[0]=100

In [ ]:
c

array([100,   1,   2,   3,   4])

In [ ]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [ ]:
e = c[3:2]

In [ ]:
e

array([], dtype=int64)

In [ ]:
c

array([100,   1,   2,   3,   4])

In [ ]:
w=c[2:3]

In [ ]:
w

array([2])

In [ ]:
  # Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) #no entiendo esto preguntar al profesor.  

[2 4]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[1:5:])

[2 3 4 5]


In [ ]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [ ]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [ ]:
# Convert list to Numpy Array
# Every element is the same type

A =np.array(a)


In [ ]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
# Show the numpy array dimensions

A.ndim

2

In [ ]:
# Show the numpy array shape

A.shape

(3, 3)

In [ ]:
# Show the numpy array size

A.size


9

In [ ]:
# Access the element on the second row and third column

A[1, 2]

23

In [ ]:
# Access the element on the second row and third column

A[1][2]

23

In [ ]:
# Access the element on the first row and first column

A[0][0]

11

In [ ]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [ ]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [ ]:
A[2,0:2]

array([31, 32])

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [ ]:
X

array([[1, 0],
       [0, 1]])

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [ ]:
# Multiply X with Y

Z = X * Y
Y
Z

array([[2, 0],
       [0, 2]])

In [ ]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [ ]:
A


array([[0, 1, 1],
       [1, 0, 1]])

In [ ]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [ ]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [ ]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [ ]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [ ]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

A=np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Write your code below and press Shift+Enter to execute
A.size

12

In [ ]:
# Write your code below and press Shift+Enter to execute
A[0][0:2]

array([1, 2])

In [ ]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

Z= np.dot(A,B)
Z

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

In [2]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

NameError: ignored

In [4]:
import numpy as np

In [5]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [6]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [7]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [8]:
A='1234567'

In [9]:
A[1::2]

'246'

In [10]:
A[1:2]

'2'

In [11]:
Name="Michael Jackson"

In [13]:
Name.find('J')

8

In [14]:
A=((11,12),[21,22])

In [15]:
A[1]

[21, 22]

In [16]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [18]:
a=set(A)

TypeError: ignored

In [19]:
A


((11, 12), [21, 22])

In [20]:
a=set(A)

TypeError: ignored

In [21]:
a


array([1, 1, 1, 1, 1])

In [22]:
Set: V={'A','B'}

NameError: ignored

In [23]:
V={'A','B'}

In [24]:
type(V)

set

In [25]:
V.add('C')

In [26]:
V

{'A', 'B', 'C'}

In [27]:
V

{'A', 'B', 'C'}

In [28]:
V.add('C')

In [29]:
V

{'A', 'B', 'C'}

In [31]:
for n in range(3):

  print(n)

0
1
2


In [32]:
def Add(x,y):

  z=y+x

  return(y)

In [33]:
x='1'
y='1'

def Add(x,y):

  z=y+x

  return(y)

In [35]:
z=y+x
z

'11'

In [36]:
Add(x,y)

'1'

In [44]:
class Points(object):

  def __init__(self,x,y):

    self.x=x

    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)
p2.x=2

p2.print_point()

x= 2  y= 2
